name: Call common build
on:
  pull_request:
    branches:
      - main

permissions:
  contents: read
  pull-requests: write
  issues: write

jobs:
  call-workflow:
    uses: dynamicweb/Common.Actions/.github/workflows/common-build.yml@main
    secrets: inherit
